---
- hosts: all
  # I find 'become' dreadfully un-descriptive; previously this was 'sudo'
  become: yes

  tasks:
    # This might have been a CentOS thing; Xubuntu is wide open by default
    #- name: Inhibit iptables-based firewall
    #  service: name=iptables state=stopped enabled=no

    - name: Check to make sure Apache created the /var/www directory
      file: path=/var/www state=directory

    - name: Enable Apache mod_rewrite
      # Not present in the version of Ansible in the Xubuntu 14.04 repos
      #apache2_module: name=rewrite state=present
      command: a2enmod rewrite
      notify: restart_apache2

    - name: Copy Apache configs for each web app
      with_items: "{{ apacheconfs }}"
      copy: src=files/sites-available/{{ item }} dest=/etc/apache2/sites-available
      notify: restart_apache2

    - name: Enable Apache 'site' for each web app
      with_items: "{{ apacheconfs }}"
      command: a2ensite {{ item }}
      notify: restart_apache2

    # This shouldn't be necessary, but to avoid problems, disable the default
    # Apache site so that there isn't any contention about which site to serve
    # for # localhost:80
    - name: Disable the default Apache site
      command: a2dissite 000-default
      notify: restart_apache2

  handlers:
    - name: restart_apache2
      service: name=apache2 state=restarted

    - name: enable_apache2_on_boot
      service: name=apache2 enabled=yes

# vim: sw=2 ts=2 expandtab
